name: CI

#on: [push]

# 在master分支发生push事件时触发。
on:
  push:
    branches:
      - master
env: # 设置环境变量
  TZ: Asia/Shanghai # 时区（设置时区可使页面中的`最近更新时间`使用时区时间）

jobs:
  build: # 自定义名称
    runs-on: ubuntu-latest # 运行在虚拟机环境ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - name: Checkout # 步骤1 拉取代码
        uses: actions/checkout@v1 # 使用的动作。格式：userName/repoName。作用：检出仓库，获取源码。 官方actions库：https://github.com/actions
      
      - name: Use Node.js ${{ matrix.node-version }} # 步骤2
        uses: actions/setup-node@v1 # 作用：安装nodejs
        with:
          node-version: ${{ matrix.node-version }} # 版本
      - name: build # 步骤3 
        run: npm install && npm run build

      - name: rsync deploy #步骤4 部署到私人服务器
        uses: burnett01/rsync-deployments@4.1
        with:
          # 这里是 rsync 的参数 switches: -avzh --delete --exclude="" --include="" --filter=""
          switches: -avzh
          path: docs/.vuepress/dist/*
          remote_path: /usr/local/nginx/html/
          remote_host: 1.15.141.114
          remote_port: 22
          remote_user: root
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}
        

      # - name: Build and Deploy # 步骤3 （只提交到github可以使用这个步骤）
      #   uses: JamesIves/github-pages-deploy-action@master # 作用：将项目构建和部署到github。 https://github.com/JamesIves/github-pages-deploy-action
      #   env: # 设置环境变量
      #     ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }} # toKen私密变量
      #     BASE_BRANCH: master # 要部署的文件夹所在的分支.
      #     BRANCH: gh-pages # 部署到的分支
      #     FOLDER: docs/.vuepress/dist # 要部署的文件夹.
      #     BUILD_SCRIPT: npm install && npm run build && cd docs/.vuepress/dist && echo 'xugaoyi.com' > CNAME && cd - # 部署前要执行的命令（记得cd进入某个目录后，后面要cd -退回开始的目录）



                # - name: run deploy.sh # 步骤3
      #   env: # 设置环境变量
      #     GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }} # toKen私密变量
      #     CODING_TOKEN: ${{ secrets.CODING_TOKEN }}
      #   run: npm install && npm run deploy


#  # 2、部署到 GitHub Pages
#       - name: Deploy
#         uses: JamesIves/github-pages-deploy-action@releases/v3
#         with:
#           ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
#           REPOSITORY_NAME: somenzz/somenzz.github.io
#           BRANCH: master
#           FOLDER: public
#           #注意这里的 public 是仓库根目录下的 public，也就是 npm run build 生成静态资源的路径，比如有的人是 `docs/.vuepress/dist`

#       # 3、同步到 gitee 的仓库
#       - name: Sync to Gitee
#         uses: wearerequired/git-mirror-action@master
#         env:
#           # 注意在 Settings->Secrets 配置 GITEE_RSA_PRIVATE_KEY
#           SSH_PRIVATE_KEY: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
#         with:
#           # 注意替换为你的 GitHub 源仓库地址
#           source-repo: git@github.com:somenzz/somenzz.github.io.git
#           # 注意替换为你的 Gitee 目标仓库地址
#           destination-repo: git@gitee.com:somenzz/somenzz.git

#       # 4、部署到 Gitee Pages
#       - name: Build Gitee Pages
#         uses: yanglbme/gitee-pages-action@main
#         with:
#           # 注意替换为你的 Gitee 用户名
#           gitee-username: somenzz
#           # 注意在 Settings->Secrets 配置 GITEE_PASSWORD
#           gitee-password: ${{ secrets.GITEE_PASSWORD }}
#           # 注意替换为你的 Gitee 仓库，仓库名严格区分大小写，请准确填写，否则会出错
#           gitee-repo: somenzz/somenzz
#           # 要部署的分支，默认是 master，若是其他分支，则需要指定（指定的分支必须存在）
#           branch: master